#
# Defines environment variables.
#
# Authors:
#   Corentin Cheminaud <corentin.cheminaud@icloud.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

# Source .zshenv.private if exists
if [[ -s "${HOME}/.zshenv.private" ]]; then
  source "${HOME}/.zshenv.private"
fi
